In [27]:
import numpy as np

print(np.__version__)

2.2.6


In [28]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [29]:
li = [5,3,2, True, "Abhinav"]
print(li)
print(type(li))

[5, 3, 2, True, 'Abhinav']
<class 'list'>


In [30]:
arr = np.array(li)
print(arr)
print(type(arr))

['5' '3' '2' 'True' 'Abhinav']
<class 'numpy.ndarray'>


In [31]:
l = [5,4,3,2,1]
larr = np.array(l)
print(larr)
print(type(larr))
print(larr.ndim)

[5 4 3 2 1]
<class 'numpy.ndarray'>
1


In [32]:
l2d = [[5,4,3], [6,7,8]]
print(l2d)
l2darr = np.array(l2d)
print(l2darr)
print(type(l2darr))
print(l2darr.ndim)

[[5, 4, 3], [6, 7, 8]]
[[5 4 3]
 [6 7 8]]
<class 'numpy.ndarray'>
2


In [33]:
mat = np.matrix(l2darr)
print(mat)
print(type(mat))
print(mat.ndim)

[[5 4 3]
 [6 7 8]]
<class 'numpy.matrix'>
2


In [34]:
mat1 = np.matrix(l)
print(l)
print(mat1)
print(mat1.ndim)

[5, 4, 3, 2, 1]
[[5 4 3 2 1]]
2


In [35]:
lnd = [[[[[2]]]]]
print(lnd)
print(type(lnd))
lndarr = np.array(lnd)
print(lndarr)
print(type(lndarr))
print(lndarr.ndim)

[[[[[2]]]]]
<class 'list'>
[[[[[2]]]]]
<class 'numpy.ndarray'>
5


In [36]:
print(mat)
print(type(mat))
matarr = np.asanyarray(mat)
print(type(matarr))
matarr = np.array(mat)
print(type(matarr))

[[5 4 3]
 [6 7 8]]
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [37]:
t = (6,4,3,2)
print(type(t))
tarr = np.array(t)
print(type(tarr))

<class 'tuple'>
<class 'numpy.ndarray'>


In [38]:
print(arr)
print(type(arr))
print(l)
print(type(l))

['5' '3' '2' 'True' 'Abhinav']
<class 'numpy.ndarray'>
[5, 4, 3, 2, 1]
<class 'list'>


In [39]:
arr = [6,5,4,3]
coparr = arr
print(arr)
print(coparr)
arr[0] = 99
print(arr)
print(coparr)

dcoparr = arr.copy()  #deep copy
print(dcoparr)

arr[0]=1000
print(arr)
print(coparr)
print(dcoparr)
print(type(arr))

[6, 5, 4, 3]
[6, 5, 4, 3]
[99, 5, 4, 3]
[99, 5, 4, 3]
[99, 5, 4, 3]
[1000, 5, 4, 3]
[1000, 5, 4, 3]
[99, 5, 4, 3]
<class 'list'>


In [40]:
np.fromfunction(lambda i, j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [41]:
arrf = np.fromfunction(lambda i, j : i*j, (4,4), dtype=int)
print(arrf)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [42]:
print(arrf)
print(arrf.shape)
print(arrf.size)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
(4, 4)
16


In [43]:
np.fromstring("4 5 3 2", sep=" ", dtype=int)

array([4, 5, 3, 2])

In [44]:
np.fromstring("abhinav, aman, somya, swati" , sep="," )

C:\Users\abhin\AppData\Local\Temp\ipykernel_12628\1153919855.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("abhinav, aman, somya, swati" , sep="," )


array([], dtype=float64)

In [45]:
s = "abhinav, aman, somya, swati"
print(s)
print(type(s))
sarr = np.array(s.split(","))
print(sarr)
print(type(sarr))

abhinav, aman, somya, swati
<class 'str'>
['abhinav' ' aman' ' somya' ' swati']
<class 'numpy.ndarray'>


In [46]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(1,10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [48]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [49]:
np.linspace(1,10,5, dtype=int)

array([ 1,  3,  5,  7, 10])

In [51]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [52]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones(4)

array([1., 1., 1., 1.])

In [57]:
np.ones((2,2,5), dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [62]:
arr = np.zeros(5, dtype=int)
print(arr)
arr = arr+5
print(arr)
arr = arr-1
print(arr)

[0 0 0 0 0]
[5 5 5 5 5]
[4 4 4 4 4]


In [69]:
diagonal = np.eye(5, dtype=int)
print(diagonal)
print(diagonal.ndim)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
2


In [80]:
np.empty(3)

array([2.44029516e-312, 2.05833592e-312, 2.22809558e-312])

In [82]:
np.array([])

array([], dtype=float64)

In [83]:
np.random.random_sample()

0.4861858444573277

In [85]:
np.random.random_sample(5)

array([0.47738802, 0.36166084, 0.99939922, 0.57936982, 0.31787213])

In [89]:
np.random.random_sample((2,3))

array([[0.91881998, 0.32830545, 0.73225991],
       [0.51488266, 0.65009605, 0.79725722]])

In [91]:
np.random.rand(1)

array([0.86024422])

In [95]:
np.random.randn(2,3)

array([[ 0.29101143,  0.54128788, -1.04663027],
       [ 1.02232824, -0.56724941, -1.69555416]])

In [97]:
np.random.randint(50)

11

In [98]:
np.random.randint(1,50)

40

In [99]:
np.random.randint(1,50, size=(5))

array([30, 32, 25,  8, 49], dtype=int32)

In [107]:
arr = np.random.randint(1,50, size=(2,3))
print(arr)

[[41 16 36]
 [32 11 47]]


In [104]:
arr.size

6

In [105]:
arr.shape

(2, 3)

In [108]:
arr.reshape(3,2)

array([[41, 16],
       [36, 32],
       [11, 47]], dtype=int32)

In [109]:
arr.reshape(1,6)

array([[41, 16, 36, 32, 11, 47]], dtype=int32)

In [110]:
arr.reshape(6,1)

array([[41],
       [16],
       [36],
       [32],
       [11],
       [47]], dtype=int32)

In [114]:
arr.reshape(2,1,3)

array([[[41, 16, 36]],

       [[32, 11, 47]]], dtype=int32)

In [117]:
arr = np.random.randint(1,50, size=16)
print(arr)

[39 40 31 38 49 46 45 39 36 17 13 23 15 40  8 44]


In [120]:
arr = arr.reshape(2,2,2,2)
print(arr)

[[[[39 40]
   [31 38]]

  [[49 46]
   [45 39]]]


 [[[36 17]
   [13 23]]

  [[15 40]
   [ 8 44]]]]


In [121]:
arr.ndim

4

In [124]:
arr>25

array([[[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True, False],
         [False, False]],

        [[False,  True],
         [False,  True]]]])

In [125]:
arr[arr>25]

array([39, 40, 31, 38, 49, 46, 45, 39, 36, 40, 44], dtype=int32)

In [126]:
arr-3

array([[[[36, 37],
         [28, 35]],

        [[46, 43],
         [42, 36]]],


       [[[33, 14],
         [10, 20]],

        [[12, 37],
         [ 5, 41]]]], dtype=int32)

In [131]:
arr[1][1]

array([[15, 40],
       [ 8, 44]], dtype=int32)

In [134]:
arr[1,1]

array([[15, 40],
       [ 8, 44]], dtype=int32)

In [137]:
arr = arr.reshape((2,8))
print(arr)

[[39 40 31 38 49 46 45 39]
 [36 17 13 23 15 40  8 44]]


In [138]:
arr[1,5]

np.int32(40)

In [139]:
arr[1][5]

np.int32(40)

In [140]:
arr[1, 0:5]

array([36, 17, 13, 23, 15], dtype=int32)

In [142]:
arr[0:2, [0,5]]

array([[39, 46],
       [36, 40]], dtype=int32)

In [147]:
arr[0:2, 0:5]

array([[39, 40, 31, 38, 49],
       [36, 17, 13, 23, 15]], dtype=int32)

In [148]:
arr1 = np.random.randint(1,5, (3,3))
arr2 = np.random.randint(1,5, (3,3))
print(arr1)
print(arr2)

[[4 1 3]
 [3 4 1]
 [1 2 3]]
[[2 2 1]
 [4 2 4]
 [2 1 1]]


In [149]:
arr1+arr2

array([[6, 3, 4],
       [7, 6, 5],
       [3, 3, 4]], dtype=int32)

In [150]:
arr1-arr2

array([[ 2, -1,  2],
       [-1,  2, -3],
       [-1,  1,  2]], dtype=int32)

In [151]:
arr1*arr2

array([[ 8,  2,  3],
       [12,  8,  4],
       [ 2,  2,  3]], dtype=int32)

In [152]:
arr1/arr2

array([[2.  , 0.5 , 3.  ],
       [0.75, 2.  , 0.25],
       [0.5 , 2.  , 3.  ]])

In [153]:
arr1,arr2

(array([[4, 1, 3],
        [3, 4, 1],
        [1, 2, 3]], dtype=int32),
 array([[2, 2, 1],
        [4, 2, 4],
        [2, 1, 1]], dtype=int32))

In [154]:
6/0

ZeroDivisionError: division by zero

In [155]:
arr1/0

C:\Users\abhin\AppData\Local\Temp\ipykernel_12628\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [156]:
#matrix multiplication
arr1@arr2

array([[18, 13, 11],
       [24, 15, 20],
       [16,  9, 12]], dtype=int32)

In [157]:
arr1,arr2

(array([[4, 1, 3],
        [3, 4, 1],
        [1, 2, 3]], dtype=int32),
 array([[2, 2, 1],
        [4, 2, 4],
        [2, 1, 1]], dtype=int32))

In [ ]:
#transpose -> converting row to cols and cols to rows
print(arr)

[[39 40 31 38 49 46 45 39]
 [36 17 13 23 15 40  8 44]]


In [159]:
arr.T

array([[39, 36],
       [40, 17],
       [31, 13],
       [38, 23],
       [49, 15],
       [46, 40],
       [45,  8],
       [39, 44]], dtype=int32)

In [161]:
print(arr)

[[39 40 31 38 49 46 45 39]
 [36 17 13 23 15 40  8 44]]


In [164]:
arr = arr.flatten()
print(arr)

[39 40 31 38 49 46 45 39 36 17 13 23 15 40  8 44]


In [170]:
np.expand_dims(arr, axis=0)

array([[39, 40, 31, 38, 49, 46, 45, 39, 36, 17, 13, 23, 15, 40,  8, 44]],
      dtype=int32)

In [175]:
arr = np.expand_dims(arr, axis=1)
print(arr)

[[39]
 [40]
 [31]
 [38]
 [49]
 [46]
 [45]
 [39]
 [36]
 [17]
 [13]
 [23]
 [15]
 [40]
 [ 8]
 [44]]


In [177]:
arr = np.squeeze(arr)
print(arr)

[39 40 31 38 49 46 45 39 36 17 13 23 15 40  8 44]


In [ ]:
np.repeat(arr,2)

array([39, 39, 40, 40, 31, 31, 38, 38, 49, 49, 46, 46, 45, 45, 39, 39, 36,
       36, 17, 17, 13, 13, 23, 23, 15, 15, 40, 40,  8,  8, 44, 44],
      dtype=int32)

In [179]:
np.repeat(arr,2,axis=0)

array([39, 39, 40, 40, 31, 31, 38, 38, 49, 49, 46, 46, 45, 45, 39, 39, 36,
       36, 17, 17, 13, 13, 23, 23, 15, 15, 40, 40,  8,  8, 44, 44],
      dtype=int32)

In [184]:
print(arr1)
np.repeat(arr1,2, axis=1)

[[4 1 3]
 [3 4 1]
 [1 2 3]]


array([[4, 4, 1, 1, 3, 3],
       [3, 3, 4, 4, 1, 1],
       [1, 1, 2, 2, 3, 3]], dtype=int32)

In [185]:
np.repeat(arr1,2, axis=0)

array([[4, 1, 3],
       [4, 1, 3],
       [3, 4, 1],
       [3, 4, 1],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [187]:
print(arr1)
np.roll(arr1, -1)

[[4 1 3]
 [3 4 1]
 [1 2 3]]


array([[1, 3, 3],
       [4, 1, 1],
       [2, 3, 4]], dtype=int32)

In [188]:
np.roll(arr1, -2)

array([[3, 3, 4],
       [1, 1, 2],
       [3, 4, 1]], dtype=int32)

In [189]:
np.roll(arr1, -3)

array([[3, 4, 1],
       [1, 2, 3],
       [4, 1, 3]], dtype=int32)

In [192]:
np.roll(arr1, -1, axis=0)

array([[3, 4, 1],
       [1, 2, 3],
       [4, 1, 3]], dtype=int32)

In [193]:
np.roll(arr1, -1, axis=1)

array([[1, 3, 4],
       [4, 1, 3],
       [2, 3, 1]], dtype=int32)

In [194]:
print(arr1)

[[4 1 3]
 [3 4 1]
 [1 2 3]]


In [195]:
d = np.array(["pw", "skills"])
print(d)


['pw' 'skills']


In [196]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [197]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [198]:
arr

array([39, 40, 31, 38, 49, 46, 45, 39, 36, 17, 13, 23, 15, 40,  8, 44],
      dtype=int32)

In [199]:
np.sin(arr)

array([ 0.96379539,  0.74511316, -0.40403765,  0.29636858, -0.95375265,
        0.90178835,  0.85090352,  0.96379539, -0.99177885, -0.96139749,
        0.42016704, -0.8462204 ,  0.65028784,  0.74511316,  0.98935825,
        0.01770193])

In [200]:
np.cos(arr)

array([ 0.26664293, -0.66693806,  0.91474236,  0.95507364,  0.30059254,
       -0.43217794,  0.52532199,  0.26664293, -0.12796369, -0.27516334,
        0.90744678, -0.53283302, -0.75968791, -0.66693806, -0.14550003,
        0.99984331])

In [202]:
np.cos(90)

np.float64(-0.4480736161291701)

In [203]:
np.log10(arr)

array([1.59106461, 1.60205999, 1.49136169, 1.5797836 , 1.69019608,
       1.66275783, 1.65321251, 1.59106461, 1.5563025 , 1.23044892,
       1.11394335, 1.36172784, 1.17609126, 1.60205999, 0.90308999,
       1.64345268])

In [204]:
np.exp(arr)

array([8.65934004e+16, 2.35385267e+17, 2.90488497e+13, 3.18559318e+16,
       1.90734657e+21, 9.49611942e+19, 3.49342711e+19, 8.65934004e+16,
       4.31123155e+15, 2.41549528e+07, 4.42413392e+05, 9.74480345e+09,
       3.26901737e+06, 2.35385267e+17, 2.98095799e+03, 1.28516001e+19])

In [207]:
np.power(arr,2)

array([1521, 1600,  961, 1444, 2401, 2116, 2025, 1521, 1296,  289,  169,
        529,  225, 1600,   64, 1936], dtype=int32)

In [208]:
np.power(arr,3)

array([ 59319,  64000,  29791,  54872, 117649,  97336,  91125,  59319,
        46656,   4913,   2197,  12167,   3375,  64000,    512,  85184],
      dtype=int32)

In [209]:
np.power(arr,1)

array([39, 40, 31, 38, 49, 46, 45, 39, 36, 17, 13, 23, 15, 40,  8, 44],
      dtype=int32)

In [210]:
np.max(arr)

np.int32(49)

In [211]:
np.mean(arr)

np.float64(32.6875)

In [212]:
np.min(arr)

np.int32(8)

In [213]:
np.std(arr)

np.float64(12.751072258833764)

In [214]:
np.var(arr)

np.float64(162.58984375)

In [216]:
np.subtract(arr1,arr2)

array([[ 2, -1,  2],
       [-1,  2, -3],
       [-1,  1,  2]], dtype=int32)

In [217]:
np.multiply(arr1,arr2)

array([[ 8,  2,  3],
       [12,  8,  4],
       [ 2,  2,  3]], dtype=int32)

In [218]:
np.mod(arr1,arr2)

array([[0, 1, 0],
       [3, 0, 1],
       [1, 0, 0]], dtype=int32)

In [219]:
np.sqrt(arr)

array([6.244998  , 6.32455532, 5.56776436, 6.164414  , 7.        ,
       6.78232998, 6.70820393, 6.244998  , 6.        , 4.12310563,
       3.60555128, 4.79583152, 3.87298335, 6.32455532, 2.82842712,
       6.63324958])

In [220]:
np.sqrt(4)

np.float64(2.0)

In [229]:
e = np.array([5,4,3,6,2,0,9,1])
print(e)

[5 4 3 6 2 0 9 1]


In [232]:
np.sort(e)

array([0, 1, 2, 3, 4, 5, 6, 9])

In [226]:
np.searchsorted(e,8)

np.int64(5)

In [230]:
np.count_nonzero(e)

7

In [235]:
e

array([5, 4, 3, 6, 2, 0, 9, 1])

In [237]:
np.where(e>2) # return index

(array([0, 1, 2, 3, 6]),)

In [241]:
np.extract(e>2, e) # return value

array([5, 4, 3, 6, 9])

In [242]:
e.byteswap()

array([360287970189639680, 288230376151711744, 216172782113783808,
       432345564227567616, 144115188075855872,                  0,
       648518346341351424,  72057594037927936])

In [243]:
import numpy.matlib as nm

nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [245]:
nm.ones((3,5), int)

matrix([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [246]:
arr1,arr2

(array([[4, 1, 3],
        [3, 4, 1],
        [1, 2, 3]], dtype=int32),
 array([[2, 2, 1],
        [4, 2, 4],
        [2, 1, 1]], dtype=int32))

In [248]:
arr1@arr2 #matrix multiplication

array([[18, 13, 11],
       [24, 15, 20],
       [16,  9, 12]], dtype=int32)

In [251]:
np.linalg.det(arr1)

np.float64(37.99999999999999)

In [252]:
np.linalg.det(arr2)

np.float64(4.0)

In [260]:
#in matrix we can't divide
np.linalg.inv(arr1)

array([[ 0.26315789,  0.07894737, -0.28947368],
       [-0.21052632,  0.23684211,  0.13157895],
       [ 0.05263158, -0.18421053,  0.34210526]])

In [261]:
a = np.array([[7,5.3,-3], [3,-5,2], [5,3,-7]])
b = np.array([16,8,0])
a,b

(array([[ 7. ,  5.3, -3. ],
        [ 3. , -5. ,  2. ],
        [ 5. ,  3. , -7. ]]),
 array([16,  8,  0]))

In [262]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])